version: '3.3'
services:
  db:
    image: postgres:14-alpine
    ports:
      - '15212:5432'
    restart: 'no'
    env_file:
      - ./.env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend-network
  service:
    image: docker.io/slackingdjaeger/jagadis-server:latest
    restart: always
    ports:
      - '3001:3001'
    volumes:
      - ./file-storage:/file-storage
      - ./log:/log
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - backend-network
volumes:
  db:
    driver: local
networks:
  backend-network:
    driver: bridge
