name: Firebase APP workflow

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  firebase_app:
    name: Run Firebase Workflow
    runs-on: ubuntu-latest ## virtual machine
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Create Service Account
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > ./client/android/app/google-services.json

      - name: Apply GMAPS API
        run: sed -i "s/MAPS_API_KEY/${{ secrets.MAPS_API_KEY }}/g" ./client/android/app/src/main/AndroidManifest.xml

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Build APK
        run: cd client && flutter pub get && flutter build apk --dart-define=API_URL=${{ secrets.API_URL }} --dart-define=FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} --dart-define=FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}

      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: ./client/build/app/outputs/apk/release/app-release.apk

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: jagadis-tester
          file: ./client/build/app/outputs/flutter-apk/app-release.apk
